export const LOCATIONS_REQUESTS = '@@LOMIS/locations/LOCATION_REQUESTS';
export const LOCATIONS_SUCCESS = '@@LOMIS/locations/LOCATION_SUCCESSS';
export const LOCATIONS_FAILURE = '@@LOMIS/locations/LOCATION_FAILURE';
